
services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3Gy5uwht4*
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - backend

  api:
    build: ./app
    container_name: flask-api
    depends_on:
      - db
    ports:
      - "${API_PORT:-5001}:5001"
    environment:
      - DB_HOST=db
      - API_PORT=${API_PORT:-5001}
    networks:
      - backend

  mcp:
    build: ./mcp
    container_name: mcp-server
    depends_on:
      - api
    ports:
      - "${MCP_PORT:-5002}:5002"
    environment:
      - API_PORT=${API_PORT:-5001}
      - MCP_PORT=${MCP_PORT:-5002}
    networks:
      - backend

networks:
  backend: