version: '3.8'

services:

  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3Gy5uwht4*
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - backend

  api:
    build: ./app
    container_name: flask-api
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
    networks:
      - backend

  mcp:
    build: ./mcp
    container_name: mcp-server
    depends_on:
      - api
    ports:
      - "5001:5001"
    networks:
      - backend

networks:
  backend:
