services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3Gy5uwht4*
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - backend

  api:
    build: ./app
    container_name: flask-api
    depends_on:
      - db
    env_file: .env
    ports:
       - "${API_PORT}:${API_PORT}"
    environment:
      - DB_HOST=db  # le nom du service `db` dans le réseau Docker
      - API_PORT=${API_PORT}
    networks:
      - backend

  mcp:
    build: ./mcp
    container_name: mcp-server
    depends_on:
      - api
    env_file: .env
    ports:
      - "${MCP_PORT}:${MCP_PORT}"
    environment:
      - API_PORT=${API_PORT}
      - MCP_PORT=${MCP_PORT}
    networks:
      - backend

networks:
  backend:
